baseURL = 'https://brandonharvey.io/'
languageCode = 'en-us'
title = 'Brandon Harvey, Los Angeles, CA'
theme = "anatole"
enableEmoji = true

[params]
title = "Brandon Harvey"
author = "Brandon Harvey"
description = """
â˜¼
"""
# profilePicture = "images/glitch-crab.png"
profilePicture = "svg/sun-solid.svg"
sidebarExtraImage = "images/brandon-profile-pic-2024.jpeg"
sidebarExtraImageAlt = "Glitch crab illustration"
displayMode = "dark"
# disableThemeSwitcher = true # Theme switcher is enabled by default
contentratio = 0.75
mainSections = ["portfolio", "art"]
# mainSections = [""]
fullPostContent = true
singleDateFormat = "2006"
indexDateFormat = "2006"
listDateFormat = "Jan 2"
customCss = ["css/custom.css", "css/styles.css"]
googleFonts = ["Inconsolata", "Michroma", "DM Sans"]
# "Syne", "Noto Sans", "Jura", 
# "Work Sans", "Space Grotesk", "Roboto:ital,wght@0,100;0,400;0,700;1,400"
reversepagetitle = true

[taxonomies]

# [menu]

#   [[menu.main]]
#   name = "portfolio"
#   identifier = "portfolio"
#   weight = 100
#   url = "/"

#   [[menu.main]]
#   name = "art"
#   identifier = "art"
#   weight = 200
#   url = "/art/"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sandover"
